<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Include_facilities</name>
   <tag></tag>
   <elementGuidId>e8835ff2-7543-4ab1-9629-d28ab2dcf685</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id=&quot;INCLUSIONS&quot;]//*[contains(text(),&quot;${includefacilities}&quot;)]</value>
   </webElementProperties>
</WebElementEntity>
