<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Inclusion</name>
   <tag></tag>
   <elementGuidId>c87313a3-47d1-44ad-ab17-bd3854ef9854</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/ul[@class=&quot;select2-results&quot;]//div[contains(text(),'France')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;content&quot;]/form/div/ul/li[2]/a</value>
   </webElementProperties>
</WebElementEntity>
