<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LocationSelection</name>
   <tag></tag>
   <elementGuidId>00318ef0-66e1-4537-b6db-9b0f4833d6b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//ul[@class=&quot;select2-results&quot;]//div[contains(text(),'France')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//ul[@class=&quot;select2-results&quot;]//div[contains(text(),'France')]</value>
   </webElementProperties>
</WebElementEntity>
