<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>add_edit_remove_checkbox</name>
   <tag></tag>
   <elementGuidId>203fae58-e230-4c83-b482-3e00b3c5fec4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@class='checkbox'][@value=&quot;${value}&quot;]/../parent::label</value>
   </webElementProperties>
</WebElementEntity>
