<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verifyadmincreated</name>
   <tag></tag>
   <elementGuidId>c83f6ffe-0bdc-421b-91b7-e90cb3d6abf4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;content&quot;]/div/div[2]/div/div/div[1]/div[2]/table/tbody/tr/td[5]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;content&quot;]/div/div[2]/div/div/div[1]/div[2]/table/tbody/tr/td[5]/a</value>
   </webElementProperties>
</WebElementEntity>
